//===-- ESPVEmitter.cpp - Generate riscv_espv_builtin_cg.inc for clang ----===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This tablegen backend is responsible for emitting riscv_espv_builtin_cg.inc
// which contains code generation for ESPV (ESP32P4 Vector) builtin intrinsics.
//
// See also the documentation in include/clang/Basic/riscv_espv.td.
//
//===----------------------------------------------------------------------===//

#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/StringMatcher.h"
#include <algorithm>
#include <vector>

using namespace llvm;

namespace clang {

void EmitESPVBuiltinCodeGen(const RecordKeeper &Records, raw_ostream &OS) {
  // Emit file header
  OS << "//===-------- riscv_espv_builtin_cg.inc - ESPV Builtin CodeGen "
        "------------===//\n";
  OS << "//\n";
  OS << "// Part of the LLVM Project, under the Apache License v2.0 with LLVM "
        "Exceptions.\n";
  OS << "// See https://llvm.org/LICENSE.txt for license information.\n";
  OS << "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception\n";
  OS << "//\n";
  OS << "//"
        "===-------------------------------------------------------------------"
        "---===//\n";
  OS << "//\n";
  OS << "// This file contains manually-written code generation for ESPV "
        "(ESP32P4 Vector)\n";
  OS << "// builtin intrinsics. This file is automatically generated from "
        "riscv_espv.td\n";
  OS << "//\n";
  OS << "// This file is included from RISCV.cpp's EmitRISCVBuiltinExpr "
        "function.\n";
  OS << "//\n";
  OS << "//"
        "===-------------------------------------------------------------------"
        "---===//\n\n";

  // Get all ESPVBuiltin records
  std::vector<const Record *> Builtins;
  for (const Record *R : Records.getAllDerivedDefinitions("ESPVBuiltin")) {
    Builtins.push_back(R);
  }

  // Sort by builtin name for consistent output
  llvm::sort(Builtins, [](const Record *A, const Record *B) {
    return A->getValueAsString("BuiltinName") <
           B->getValueAsString("BuiltinName");
  });

  // Emit each builtin case
  for (const Record *R : Builtins) {
    StringRef BuiltinName = R->getValueAsString("BuiltinName");
    StringRef ManualCodegen = R->getValueAsString("ManualCodegen");

    // Emit case statement
    OS << "    case RISCV::BI__builtin_riscv_esp_" << BuiltinName << ": {\n";

    // Emit the manual codegen code with proper indentation
    // The ManualCodegen field contains the C++ code
    std::string Code = ManualCodegen.str();

    // Remove leading/trailing whitespace but preserve internal structure
    Code = StringRef(Code).trim().str();

    // Output the code with proper indentation (add 6 spaces for case block)
    if (!Code.empty()) {
      SmallVector<StringRef, 32> Lines;
      StringRef(Code).split(Lines, '\n');
      for (StringRef Line : Lines) {
        OS << "      " << Line << "\n";
      }
    }

    OS << "    }\n\n";
  }
}

} // end namespace clang
